### ISSUE TITLE
Push current Github version to CPAN

### ISSUE THREAD

**Issue by a3f** [JaHIY/Crypt-XTEA#3]
My pull request https://github.com/JaHIY/Crypt-XTEA/pull/2 was merged, but the new version wasn't pushed to CPAN.

 [`Crypt::ECB` ](http://search.cpan.org/~appel/Crypt-ECB/ECB.pm) now expects `blocksize` and `keysize` to be subroutines and my code doesn't work anymore.

**Comment by JaHIY** [comment]
Sorry for my mistake.

[Crypt::XTEA](https://metacpan.org/pod/Crypt::XTEA) in CPAN has upgraded to 0.0108.
